check the trainable type for Layer init
keras-team/keras pull request #14924
Opened 2021-07-13 22:45 UTC by haifeng-jin

2021-07-14 00:35 UTC, fchollet requested changes
Thanks for the PR!

2021-07-14 00:35 UTC, fchollet commented on keras/engine/base_layer.py
> +      raise TypeError('Expect trainable to be a boolean, got ' + str(trainable))
Use a f-string for string formatting

2021-07-14 00:35 UTC, fchollet commented on keras/engine/base_layer.py
> +    if not isinstance(trainable, bool):
The `trainable` argument should also support a scalar boolean `tf.Variable`.

In addition, there is a risk here that some people might be passing `0` or `1` and would then see their code break. We would need to run a global TAP to check for such cases.

2021-07-14 00:35 UTC, fchollet commented on keras/engine/base_layer_test.py
> +    with self.assertRaises(TypeError) as e:
Any `assertRaises` should use a regex to check that the error being raised is the one you expect (and not another error upstream)

2021-07-15 22:46 UTC, fchollet approved these changes
LGTM, thanks. When merging we'll need to patch the CL and run a global TAP.

2021-07-15 22:51 UTC, haifeng-jin commented
@fchollet One more commit for using the regex to match the error message is in.

2021-07-20 18:31 UTC, haifeng-jin commented
Will submit internally.

2021-07-20 18:31 UTC, closed without merging