Add efficientnet v2 to keras.applications
keras-team/keras pull request #14935
Opened 2021-07-16 06:29 UTC by sebastian-sz

### Description

This PR adds EfficientNetV2 model architecture to `keras.applications`.

[Arxiv link](https://arxiv.org/abs/2104.00298)
[Reference implementation](https://github.com/google/automl/blob/master/efficientnetv2/effnetv2_model.py)

The code is heavily inspired by already existing code from `efficientnet.py` and `efficientnet_weight_update_util.py`. I tried to make it as similar to existing codebase as possible.

The models were rewritten using Keras functional API, and the weights were converted via modified weights conversion script.

### Motiviation
Adding EfficientNetV2 models to `keras.applications` has been discussed on Tensorflow's github:
https://github.com/tensorflow/tensorflow/issues/50054 

It was mentioned that this family of models would be welcomed in `keras.applications`, hence this contribution.

### Usage / Changes
The models could be used similarly to other models in `keras.applications`
```python
from keras.applications import efficientnet_v2

model = efficientnet_v2.EfficientNetV2_S()
```
### Todos / Known Issues
1. The output consistency was measured on a single panda image, from the original repository. It's worth noting that original repository performs cropping for some input sizes - I did not include this cropping here.
2. I did not use preprocessing layers, as I thought some users might experiment with different preprocessing. But they can be added.
3. Right now, I'm hosting the weights on GCP bucket but I won't be able to do this forever :(

2021-07-16 17:30 UTC, qlzh727 commented
Thanks for sending the PR, it will take us sometime to verify the details here. For the model weights, could you also attach them in the PR? (we can upload them to the keras-team gcs buckets, and then you can update the URL in the PR).

2021-07-17 12:26 UTC, sebastian-sz commented
Thanks for the response. If I can help by answering any questions, let me know.

I'm having hard time attaching the weights on GitHub, so here is a Google Drive link: 
https://drive.google.com/file/d/1AYx_2zNyQGpYmcbsVeN1PewNUg999H8C/view?usp=sharing

2021-08-12 08:43 UTC, leondgarse commented
It's good to have `efficientnetV2` directly usable form `keras.applications`. I have these model weights converted and uploaded in my own repo [leondgarse/keras_efficientnet_v2](https://github.com/leondgarse/keras_efficientnet_v2), including all `imagenet` / `imagenet-21k` / `imagenet21k-ft1k` pre-trained weights, and also `efficientnetv2-xl` weights. Hope this can help.

2021-09-10 12:35 UTC, innat commented
@mingxingtan cc. @gbaned @qlzh727 
Could you please review or iterate over this [`efficientnet v2`](https://github.com/google/automl/tree/master/efficientnetv2) implementation? 
FYI, It's been implemented with functional API and not with the official way (subclassed API).

2021-09-24 03:46 UTC, mingxingtan reviewed
Thanks for adding it. Overall looks good to me!

2021-09-24 03:46 UTC, mingxingtan commented on keras/applications/efficientnet_v2.py
> +# Copyright 2019 The TensorFlow Authors. All Rights Reserved.
should it be 2021?

2021-09-24 03:46 UTC, mingxingtan commented on keras/applications/efficientnet_v2_weight_update_util.py
> +# Copyright 2020 The TensorFlow Authors. All Rights Reserved.
should it be 2021?

2021-09-30 15:27 UTC, innat commented
@qlzh727 @mattdangerw 
Any update on this PR?

2021-10-01 00:05 UTC, fchollet requested changes
Thanks for the PR, this is great, let's ship it.

> The output consistency was measured on a single panda image, from the original repository. It's worth noting that original repository performs cropping for some input sizes - I did not include this cropping here.

Have you evaluated the model (with pretrained weights loaded) on the ImageNet validation set? What top-5 accuracy and accuracy do you get?

> Right now, I'm hosting the weights on GCP bucket but I won't be able to do this forever :(

We would download the files and re-host them in our own buckets as part of the merging process.

Also, keep in mind that once the application is submitted, you should update the keras.io docs with information about it: https://keras.io/api/applications/

2021-10-01 00:05 UTC, fchollet commented on keras/applications/efficientnet_v2.py
> +def preprocess_input(x, data_format=None):  # pylint: disable=unused-argument
Our current policy is to *not* have a preprocessing function for new applications.

This function should just be pass-through, e.g.

```
def preprocess_input(x):
   return x
```

Meanwhile, the application itself should include a `Rescaling` layer as its first layer.

The goal being that applications should be able to process raw images, without the user having to care about what the correct preprocessing scheme to use is.

See e.g. 
https://github.com/keras-team/keras/blob/master/keras/applications/mobilenet_v3.py#L281-L282

Also include the following argument to make the Rescaling layer optional:

```
include_preprocessing: Boolean, whether to include the preprocessing
      layer (`Rescaling`) at the start of the network. Defaults to `True`.
```

https://github.com/keras-team/keras/blob/master/keras/applications/mobilenet_v3.py#L145

2021-10-01 06:28 UTC, sebastian-sz commented
@fchollet @mingxingtan 
Thank you for the review. In the nearest future I'll read the comments and fix the code.

2021-10-01 06:29 UTC, sebastian-sz commented on keras/applications/applications_load_weight_test.py
> +                        efficientnet_v2.EfficientNetV2_L])
If you prefer I can delete S, M, L variants. Let me know.

2021-10-01 07:44 UTC, innat commented on keras/applications/applications_load_weight_test.py
> +                        efficientnet_v2.EfficientNetV2_L])
@fchollet isn't it ok to keep all the v2 model's variants? In v1, it's included almost all. Also, in v2, the variants of `s`, `m`, `l` and `xl` have much higher top-1 accuracy compare to the rest (`bs`).

2021-10-01 17:30 UTC, mattdangerw requested changes
Thanks for the PR! I think Francois covered the main changes, but made a pass for style as well.

2021-10-04 10:02 UTC, sebastian-sz commented on keras/applications/efficientnet_v2.py
> +        - `avg` means that global average pooling
@mattdangerw I'm getting a bit confused with the backticks and string literals conventions. 
On line 836, you mentioned:
> `'imagenet' (pre-training on ImageNet),`
> surround string literal with backticks

but here, you mention that string literal should be surrounded by single quote `'avg'`.

1. Should this be surrounded by single quote?
2. Should I also change None and max parameters to be surrounded with single quote?

2021-10-04 19:17 UTC, sebastian-sz commented on keras/applications/efficientnet_v2.py
> +      # Warning. Is local pooling always false?
Sorry, I forgot to delete this. 

As far as I know `local_pooling` is always false. You can check my analysis workflow [here](https://colab.research.google.com/drive/1bdyTwSc5raoWY2-9obm6oMAzvsm87i19?usp=sharing).

2021-10-04 19:31 UTC, mattdangerw commented on keras/applications/efficientnet_v2.py
> +        - `avg` means that global average pooling
Oh sorry, I meant add the quotes along with the backticks here as well. It is just that github is grabbing my backticks and rendering them as markdown.

A string literal should be surrounded by backticks and quoted. None should be surrounded by backticks and not quoted. So \`'avg'\`, \`'max'\` and \`None\`.

Basically anything inside the backticks should be valid python you could pass for the argument in question.

2021-10-04 19:33 UTC, sebastian-sz commented on keras/applications/efficientnet_v2.py
> +        survival_probability=drop_connect_rate * b / blocks,  # Is this ok? Copied from V1.
@fchollet 
I checked again and It should be ok.

V1 code:
```python
if survival_prob:
  drop_rate = 1.0 - survival_prob
  survival_prob = 1.0 - drop_rate * float(idx) / len(self._blocks)
  logging.info('block_%s survival_prob: %s', idx, survival_prob)
```

V2 equivalent:
```python
if survival_prob:
  drop_rate = 1.0 - survival_prob
  survival_prob = 1.0 - drop_rate * float(idx) / len(self._blocks)
  logging.info('block_%s survival_prob: %s', idx, survival_prob)
```

Sources:
V1: https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/efficientnet_model.py#L656
V2: https://github.com/google/automl/blob/master/efficientnetv2/effnetv2_model.py#L617

2021-10-05 05:36 UTC, sebastian-sz commented on keras/applications/efficientnet_v2.py
> +        - `avg` means that global average pooling
Understood, thanks!

If you don't mind me asking one more question: 
Should I indent my code everywhere with 2 spaces instead of 4?

2021-10-07 07:34 UTC, sebastian-sz commented
I updated the PR based on the comments. Let me know if this is ok.

### Model evaluation
> Have you evaluated the model (with pretrained weights loaded) on the ImageNet validation set? What top-5 accuracy and accuracy do you get?

Sadly no. I don't have the data and compute to run it, but I can help setting up the scripts.

### Weights hosting
> We would download the files and re-host them in our own buckets as part of the merging process.

I had to remove the weights from my end. Here is the [Google Drive link](https://drive.google.com/file/d/1UCtqTFQ5G-eg1LoK08qxTq3t-O-h0Sib/view?usp=sharing) with updated weights.

### Model variants.
> Do we really need all these models? Why not just the Bs (like for v1)?

Personally I wouldn't mind `S/M/L` variants but if you want them deleted I will remove them.
How should I proceed? Delete `S/M/L` variants, leave as is, or add `XL` to all variants?

2021-10-29 20:58 UTC, merged

2021-10-31 18:49 UTC, sebastian-sz commented
@mattdangerw 
Sorry to interrupt, I can see that the PR is merged, but what about the weights upload and download path?

2021-11-01 17:39 UTC, mattdangerw commented
@sebastian-sz I update the code during submission to point to `"https://storage.googleapis.com/tensorflow/keras-applications/efficientnet_v2/"`. Which has the weights from the google drive folder you shared. Updating those weights (and hashes) will need to be done by someone on the Keras team with write access to the bucket.

2021-11-02 06:25 UTC, sebastian-sz commented
@mattdangerw Got it, thanks for the clarification!

2021-11-05 13:54 UTC, innat commented
@sebastian-sz I've noticed that EffNetV2-XL is released. Will it also be included here? It's the big model I guess.

2021-11-05 14:08 UTC, sebastian-sz commented
> @sebastian-sz I've noticed that EffNetV2-XL is released. Will it also be included here? It's the big model I guess.

@innat 
This is merged so I guess it can be added in a separate PR. 
The model is so big that there are two problems:
1. Current naming convention will fail due to huge number of layers. One needs to change:
from 
`name="block{}{}_".format(i + 1, chr(j + 97)),`
to something like
`name=f"block{i+1}-{j+1:02d}_",` 

The weights should not need to be reuploaded, but XL variant must be converted.

2. RecursionError
The model has so many layers that creating it directly:
```python
def EfficientNetV2XL(
    include_top=True,
    weights="imagenet",
    input_tensor=None,
    input_shape=None,
    pooling=None,
    classes=1000,
    classifier_activation="softmax",
):
    """Create EfficientNetV2 XL variant."""

    return EfficientNetV2(
        width_coefficient=1.0,
        depth_coefficient=1.0,
        default_size=512,
        model_name="efficientnetv2-xl",
        # (...)
    )
```
will throw `RecursionError`. One can increase recursion limit:
```python
current_limit = sys.getrecursionlimit()
    target_limit = 2000
    if current_limit < target_limit:
        sys.setrecursionlimit(target_limit)
```

but I don't know if it's a bug or there is a better way to handle this.

2021-11-05 17:09 UTC, innat commented
@sebastian-sz Are [these ](https://github.com/sebastian-sz/efficientnet-v2-keras/releases)the exact weights file that will be used in `tf.keras.applicaitons` API?

2021-11-05 18:18 UTC, sebastian-sz commented
@innat 

### About the weights
Very similar - the model's architecture is the same apart for few code differences - but not exactly the same.  
The differences are:
* weights in the link don't have preprocessing layer in the model (although this should not be an issue)
* different block naming - weights in the link use the one I mentioned
* weights in the link do not use EMA for easier comparison. In this PR I included EMA as I've heard somewhere they are preffered and even slightly better.
* Slightly different weight conversion script: for this PR i used [this script](https://gist.github.com/sebastian-sz/dc349b933a3b9bb1906773e1608c3acb). 

### About the issue
They do not have this Issue in the original repo as they use subclassing API. I guess in subclassing API there are fewer loops as they are only stacking blocks (e.g. STEM might be treated as a single layer). Functional API (this PR + my repo) is stacking raw layers (e. g. conv2D) layer after layer. 

I will open the Issue on Keras repo with an example and see what the devs say.