doc: add link to SciKeras migration guide
keras-team/keras pull request #15723
Opened 2021-11-29 21:28 UTC by adriangb

Add a direct link to SciKeras' migration guide to mitigate user confusion over the small differences between the wrappers

2021-12-01 20:03 UTC, haifeng-jin approved these changes
Thanks for the PR! LGTM

2021-12-01 20:25 UTC, haifeng-jin requested changes
Seems there are 4 lines over 80 characters. Would you please change them? Thanks.

2021-12-01 20:55 UTC, adriangb commented
shorten lines

2021-12-01 21:00 UTC, adriangb commented
Ok should be all set!

2021-12-02 00:44 UTC, haifeng-jin approved these changes

2021-12-02 05:25 UTC, merged