Added new update_state for class Mean() and Sum()
keras-team/keras pull request #16376
Opened 2022-04-07 11:23 UTC by wellsonah2019

There was a small bug found [on using metrics such as Mean() and Sum() #16291](https://github.com/keras-team/keras/issues/16291)  when fitting a model. This new fix was inspired by [this Stack Overflow post](https://stackoverflow.com/questions/68354367/getting-an-error-when-using-tf-keras-metrics-mean-in-functional-keras-api) where they re-introduced the function with correct parameters so that the multiple values error will no longer show up.

2022-04-08 21:30 UTC, fchollet requested changes
Thanks for the PR.

> There was a small bug found https://github.com/keras-team/keras/issues/16291 when fitting a model

What would be a simple unit test to demonstrate the issue? If we introduce a fix, we also need a test, otherwise we may end up reverting the fix in the future.

2022-04-09 11:39 UTC, wellsonah2019 commented
@fchollet,

I have made a [google colab](https://colab.research.google.com/gist/wellsonah2019/931048f5b4ada6db49b450fc227cf00f/untitled272.ipynb#scrollTo=0WvEx66cHZJ5) to show the errors and how the fixed version of the classes (which is what I have put in the pull request) does not show the error anymore.

Please let me know if this is sufficient to be a unit test and if you are unable to access the google colab notebook.

Thanks!

2022-04-10 04:28 UTC, fchollet commented
Sure, that's fine as a test. In the test code, please make sure to reference the issue on GitHub for context.

2022-04-10 23:02 UTC, fchollet requested changes
Thanks for the update. Generally speaking, this is not how to write unit tests. You should not use `print` statements or `try`/`except` statements. And you should follow our style guide.

You can just use the following:

```
  def test_training_with_mean_and_sum(self):
      inputs = keras.Input(shape=(1,))
      outputs = keras.layers.Dense(1)
      model = keras.Model(inputs, outputs)

      model.compile(optimizer='rmsprop',
                    loss='mse',
                    metrics=[keras.metrics.Sum(),
                             keras.metrics.Mean()])
      model.fit(np.ones((2, 1)), np.ones((2, 1)))
```

Also move the test to the class that tests the `Mean` and `Sum` classes.

2022-04-10 23:08 UTC, fchollet reviewed
Upon closer inspection of the PR, I realize that the issue it's trying to fix isn't an issue at all. The signature for `Mean.update_state()` is supposed to be `update_state(self, samples, sample_weight=None)`. You cannot call it with 2 values. `Mean(y_true, y_pred)` is ill-defined since you can't know if you want to take the mean of `y_true` or `y_pred`.

The current code is correct. The issue is passing `Mean` or `Sum` to `compile()`: the behavior is ill-defined.

2022-04-10 23:08 UTC, closed without merging

2022-04-11 05:39 UTC, wellsonah2019 commented
@fchollet,

I see. Thank you for explaining. In that case, will the Keras team implement an exception to tell them not to use Mean or Sum if users try to compile with those metrics to prevent them from getting this update_state error?