Fix missed parameter from AUC config
keras-team/keras pull request #16499
Opened 2022-05-05 15:25 UTC by weipeilun

AUC metrics missed `from_logits` parameter in `get_config` method, which will cause a error when load from a saved model and `from_logits` is True.

2022-05-09 16:38 UTC, qlzh727 requested changes
Thanks for the fix. Could u add a unit test to cover this case.

2022-05-09 18:24 UTC, fchollet reviewed
Thanks for the PR! Could you add a unit test (saving and loading the metric and checking that the behavior is the same)?

2022-05-18 06:15 UTC, weipeilun commented
@qlzh727 @fchollet Thanks for the comment. A unit test is added and another parameter missed is found, thanks again.

2022-05-18 20:42 UTC, qlzh727 requested changes
Thanks for the change.

2022-05-18 20:42 UTC, qlzh727 commented on keras/metrics/metrics_test.py
> +class AUCTest(tf.test.TestCase):
You can move this to the confusion_matrix_test.py, which has a AUCTest class.

2022-05-19 08:44 UTC, weipeilun commented
@qlzh727 I moved the test case to confusion_matrix_test.py, again found a error caused by dtype mismatch of weights and labels when calling update_state(). Please review that too, thanks.

2022-06-15 19:59 UTC, qlzh727 approved these changes
Thanks for the PR and sorry for the wait.

2022-06-16 19:03 UTC, merged