Added identity layer
keras-team/keras pull request #17251
Opened 2022-11-17 05:32 UTC by AdityaKane2001

@fchollet @qlzh727 

Please see #16745. Added input agnostic Identity layer.

2022-11-17 19:12 UTC, fchollet reviewed
Thanks for the PR!

2022-11-17 19:12 UTC, fchollet commented on keras/layers/core/identity.py
> +    def __init__(*args, **kwargs):
No need for `__init__()`

2022-11-18 05:08 UTC, AdityaKane2001 commented
@fchollet 

Made requested changes.

2022-11-22 07:56 UTC, AdityaKane2001 commented
@fchollet Could you please take a look at this one? TIA

2022-11-28 18:34 UTC, qlzh727 commented
It seems that https://github.com/keras-team/keras-cv/issues/425 is already closed with other fixes. Do we still need this layer?

2022-11-28 18:35 UTC, AdityaKane2001 commented
Not for KerasCV, but is worthwhile as a general addition IMO.

2022-11-28 18:35 UTC, AdityaKane2001 commented
#16745 has the full discussion iirc.

2022-11-30 04:51 UTC, fchollet reviewed
Sorry for the delay, thanks for the updates

2022-11-30 04:51 UTC, fchollet commented on keras/layers/core/identity.py
> +    Args:
You can list `name` here to avoid `None` (which would not render properly on the website)

2022-11-30 04:51 UTC, fchollet commented on keras/layers/core/identity.py
> +    def call(self, inputs, *args, **kwargs):
Just `inputs`

2022-11-30 04:59 UTC, AdityaKane2001 commented
@fchollet 

Made requested changes.

2022-11-30 18:42 UTC, fchollet commented on keras/layers/core/identity.py
> +    performed. The layer is argument insensitive, and returns only the
"and returns its `inputs` argument as output"

2022-11-30 18:43 UTC, fchollet requested changes
> This branch cannot be rebased due to conflicts

Please rebase.

2022-11-30 19:01 UTC, fchollet commented
> This branch cannot be rebased due to conflicts

Unfortunately I'm still seeing the merge conflict. If you can't fix it you can try recreating a PR from a fresh fork.

2022-11-30 19:03 UTC, AdityaKane2001 commented
>  Unfortunately I'm still seeing the merge conflict. If you can't fix it you can try recreating a PR from a fresh fork.

Works, I'll make a new PR.

2022-11-30 19:15 UTC, AdityaKane2001 commented
@fchollet 

Please see #17291.

2022-11-30 20:18 UTC, closed without merging