Warning if categorical crossentropy is used for 2 labels
keras-team/keras pull request #17330
Opened 2022-12-12 08:35 UTC by old-school-kid

solves #17029 
[Solution colab notebook](https://colab.research.google.com/drive/1nUBPGfLs2CGs6LjA2_luscuWadZ0kwnQ?usp=sharing)
Raised a warning and not an error. 

Also `CategoricalHinge` loss could have the same problem but apparently the documentation itself cites an 1D tensor as an example. It should be noted that the example given in the doc returns `1.4` as answer while the correct answer is `1.3`

cc @haifeng-jin

2022-12-12 15:25 UTC, haifeng-jin requested changes
Thanks for the PR! Would you please add a unit test for the warning?

2022-12-25 06:08 UTC, old-school-kid commented
@haifeng-jin 
Sorry for the delay. Please take a look now.

2022-12-25 19:25 UTC, haifeng-jin requested changes
Thanks for the update!

2022-12-25 19:25 UTC, haifeng-jin commented on keras/losses_test.py
> +            assert issubclass(w[-1].category, SyntaxWarning)
Let's use `self.assertIsInstance(w[-1].category, SyntaxWarning)`.

2022-12-25 19:25 UTC, haifeng-jin commented on keras/losses_test.py
> +            assert "Recieved an one-dimensional output..*" in str(w[-1].message)
Let's use `self.assertIn(your_string, w[-1].message)`.

2022-12-25 19:25 UTC, haifeng-jin commented on keras/losses.py
> +            "if you have only 2 labels",
Usually we do the strings in the following format:
```py
f"Expected something to be something. Received: {something}."
```
So my suggestion would be:
```py
"Expected the tensor's shape passed to 'categorical_crossentropy' to be (batch_size, n_classes), "
f"where n_classes > 1. Received: y_pred.shape={y_pred.shape}. "
"Consider using 'binary_crossentropy' if you only have 2 classes."
```

See if @fchollet have comments on this part.

2023-01-10 18:44 UTC, haifeng-jin approved these changes
Looks good to me! We will see @fchollet review before merging.

2023-01-10 23:38 UTC, fchollet reviewed
Thanks for the PR!

2023-01-10 23:38 UTC, fchollet commented on keras/losses.py
> +            SyntaxWarning,
Add `stacklevel=2` argument

2023-01-10 23:38 UTC, fchollet commented on keras/losses.py
> +            "Consider using 'binary_crossentropy' if you only have 2 classes.",
```
"In loss categorical_crossentropy, expected "
"y_pred.shape to be (batch_size, num_classes) "
f"with num_classes > 1. Received: y_pred.shape={y_pred.shape}. "
"Consider using 'binary_crossentropy' if you only have 2 classes.",
```

2023-01-13 00:11 UTC, haifeng-jin commented
@old-school-kid 
I have created https://github.com/old-school-kid/keras/pull/3 .
You can merge it and the tests are fixed.

2023-01-13 20:10 UTC, merged

2023-01-13 20:42 UTC, haifeng-jin commented
Hi @old-school-kid , the PR has been merged. Thank you again for your contribution!
Would you help us answer the following questions so that we can improve the contributor experience?
* What editor did you use to edit the code?
* Did you find it hard to setup the environment, run the tests, or format the code?

Any other feedback are also appreciated.