keras.models.clone_model creates different weight names for RNN layers
keras-team/keras pull request #17465
Opened 2023-01-24 08:09 UTC by mergian

This pull request fixes: #17433

It's the easiest solution I came up with.

Another solution would be to add `cell_name` argument to all RNN layers, but that changes the API.

I'm not sure if 'cell' should be used as name, or if we should stick to 'simple_rnn_cell', 'lstm_cell', 'gru_cell' instead.

It also works with saving models AND also when loading old saved models. As in this case, the RNN cell's name is stored in the saved model, so it will correctly be loaded.

2023-01-24 17:38 UTC, qlzh727 requested changes
Thanks for the PR. Please format you PR as well.

2023-01-25 18:01 UTC, qlzh727 requested changes

2023-01-25 18:01 UTC, qlzh727 commented on keras/layers/rnn/base_conv_lstm.py
> +            name="lstm_cell",
This should be conv_lstm_cell I think.

2023-01-26 06:29 UTC, mergian commented on keras/layers/rnn/base_conv_lstm.py
> +            name="lstm_cell",
Yes you are right 🤦🏻‍♂️

2023-01-26 17:46 UTC, qlzh727 approved these changes

2023-02-15 17:43 UTC, qlzh727 approved these changes

2023-02-15 21:36 UTC, merged