keras.layers.Bidirectional constructor ignores trainable argument, causing models with trainable=False layers to incorrectly be cloned
keras-team/keras pull request #17467
Opened 2023-01-24 08:25 UTC by mergian

This PR fixes #17466.

2023-01-24 17:42 UTC, qlzh727 requested changes
Thanks for the PR.

2023-01-24 17:42 UTC, qlzh727 commented on keras/layers/rnn/bidirectional_test.py
> +        assert clone_trainable.get_config() == model.get_config()
Please use `self.assertEqual()` instead.

2023-01-24 17:42 UTC, qlzh727 commented on keras/layers/rnn/bidirectional_test.py
> +        assert clone_untrainable.get_config() == model.get_config()
Same here.

2023-01-24 17:42 UTC, qlzh727 commented on keras/layers/rnn/bidirectional_test.py
> +
Can you also add a test to create a `keras.layers.Bidirectional` with a trainable = False in the __init__ arg?

2023-01-25 07:19 UTC, mergian commented
I changed `self._trainable` to `= kwargs.get('trainable', layer.trainable)` as also other attributes get fetched from the layer. I also changed the test cases to test for these behavior.

2023-01-25 17:50 UTC, qlzh727 approved these changes

2023-01-27 18:58 UTC, merged