Move `Defaults to` to end of arg docstring and standardise values
keras-team/keras pull request #17748
Opened 2023-03-31 04:32 UTC by SamuelMarks

I've written a Python compiler that can do a bunch of thing. Relevant to Keras I am turning TensorFlow into SQL tables by way of SQLalchemy:
```sh
# TensorFlow 2.12.0
$ python3 -m cdd exmod --module 'tensorflow.keras.optimizers' \
                       --emit 'sqlalchemy_table' \
                       -o '/tmp/tf_optimizers'
```

After deduplicating and running `black` here are the contents of `sgd.py`:
```py
"""
Generated from keras.optimizers.sgd.
"""

SGD = Table(
    "SGD",
    metadata,
    Column(
        "learning_rate",
        Float,
        comment="A `Tensor`, floating point value, or a schedule that is a `tf.keras.optimizers.schedules.LearningRateSchedule`, or a callable that takes no arguments and returns the actual value to use. The learning rate",
        default=0.001,
        nullable=False,
    ),
    Column(
        "momentum",
        String,
        comment="float hyperparameter >= 0 that accelerates gradient descent in the relevant direction and dampens oscillations.e., vanilla gradient descent",
        default="0, i",
        nullable=False,
    ),
    Column(
        "nesterov",
        Boolean,
        comment="boolean. Whether to apply Nesterov momentum",
        default=False,
        nullable=False,
    ),
    Column("clipnorm", default=None, nullable=True),
    Column("clipvalue", default=None, nullable=True),
    Column("use_ema", Boolean, default=False, nullable=False),
    Column("ema_overwrite_frequency", default=None, nullable=True),
    Column("weight_decay", default=None, nullable=True),
    Column("global_clipnorm", default=None, nullable=True),
    Column("ema_momentum", Float, default=0.99, nullable=False),
    Column("jit_compile", Boolean, default=True, nullable=False),
    Column("name", String, default="SGD", nullable=False),
    Column("id", Integer, primary_key=True, server_default=Identity()),
)

__all__ = ["SGD"]
```

As you can see, `momentum` has an incorrect value because of how you've written your docstrings:
https://github.com/keras-team/keras/blob/0f8e81f/keras/optimizers/sgd.py#L62

Some commentary on the `Defaults to` syntax as understood by Sphinx:
- https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html#the-sphinx-docstring-format
- https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

---

So this PR rewrite your docstrings to put the `Defaults to` at the end and limit it to one value or a boolean condition.

PS: I also noticed inconsistent use of backticks. Did you want them everywhere? - This would disambiguate floats from integers I guess

2023-04-03 17:44 UTC, qlzh727 requested changes
Thanks for the PR. Since this is quite large at the moment, is it possible to split this into smaller ones (one PR per package), so that we can speed up the review (sending to multiple team member.)?

2023-04-04 02:09 UTC, SamuelMarks commented
@qlzh727 I can, in the past I had a script to turn one PR into one per file and that got through all the hoops until they reached TensorFlow master.

So you want me to do that here? - Happy to. - Maybe I'll link back here in case others want to chime in about repository-wide standards? - Also if any dis/agreements of this approach were to be made, maybe make them on this issue #17748

2023-04-06 17:30 UTC, qlzh727 commented
Hi @SamuelMarks, I think the one-file per PR is causing too much overhead for the review.

1. Please stop creating any new PR for now.
2. For any PR that has not been approved, please close them.
3. Once we merge all the in flight PR, please create one PR per package (eg one for all files keras/layers/convolution).

2023-04-06 20:06 UTC, closed without merging

2023-04-06 21:24 UTC, SamuelMarks commented
@qlzh727 I can do that. In the meantime this branch is now up-to-date with all the other PRs I sent.

```sh
# Checkout, because `git merge --no-commit --strategy-option theirs`
# doesn't work without octopus
$ while read -r b; do
    f="${b//.//}"; f="${f/-defaults-to/.py}"
    git checkout "$b" -- "$f"
done< <(git branch -a | grep -F ' keras')

# Branch names, run from `defaults-to` branch
$ while read -r name; do
    branch="${name//\//.}"; branch="${branch::-3}-defaults-to"
    echo -n "$branch"
done< <(git diff --name-only)
```

FYI: I hadn't made new PRs in 2 days I think you misconfigured copybara on your end.

So I'll make new PRs, one for each directory this time? - Should be scriptable.

2023-04-06 21:25 UTC, SamuelMarks commented
@qlzh727 I can do that. In the meantime this branch is now up-to-date with all the other PRs I sent.

```sh
# Checkout, because `git merge --no-commit --strategy-option theirs`
# doesn't work with octopus
$ while read -r b; do
    f="${b//.//}"; f="${f/-defaults-to/.py}"
    git checkout "$b" -- "$f"
done< <(git branch -a | grep -F ' keras')

# Branch names, run from `defaults-to` branch
$ while read -r name; do
    branch="${name//\//.}"; branch="${branch::-3}-defaults-to"
    echo -n "$branch"
done< <(git diff --name-only)
```

FYI: I hadn't made new PRs in 2 days I think you misconfigured copybara on your end.

So I'll make new PRs, one for each directory this time? - Should be scriptable.

2023-04-06 21:26 UTC, SamuelMarks commented
@qlzh727 I can do that. In the meantime this branch is now up-to-date with all the other PRs I sent.

```sh
# Checkout, because `git merge --no-commit --strategy-option theirs`
# doesn't work with octopus
$ while read -r b; do
    f="${b//.//}"; f="${f/-defaults-to/.py}"
    git checkout "$b" -- "$f"
done< <(git branch -a | grep -F ' keras')

# Branch names
$ while read -r name; do
    branch="${name//\//.}"; branch="${branch::-3}-defaults-to"
    echo -n "$branch"
done< <(git diff --name-only)
```

FYI: I hadn't made new PRs in 2 days I think you misconfigured copybara on your end.

So I'll make new PRs, one for each directory this time? - Should be scriptable.

2023-04-06 21:33 UTC, SamuelMarks commented
@qlzh727 I can do that. In the meantime this branch is now up-to-date with all the other PRs I sent.

```sh
# Checkout, because `git merge --no-commit --strategy-option theirs`
# doesn't work with octopus
$ while read -r b; do
    f="${b//.//}"; f="${f/-defaults-to/.py}"
    git checkout "$b" -- "$f"
done< <(git branch -a | grep -F ' keras')

# Branch names
$ while read -r name; do
    branch="${name//\//.}"; branch="${branch::-3}-defaults-to"
    echo -n "$branch"
done< <(git diff --name-only)
```

FYI: I hadn't made new PRs in 2 days I think you misconfigured copybara on your end.

So I'll make new PRs, one for each directory this time? - Should be scriptable. From a glance, after merging `master`:
```sh
$ git diff --name-only | wc -l
112
$ git diff --name-only | xargs -n1 dirname | sort -u | wc -l
26
```

So will be sending 26 new pull requests. I'll wait a little bit [14 hours?] for whatever is in the queue to be merged|closed.

2023-04-13 00:48 UTC, SamuelMarks commented
Sent through the PRs. Here's how:
```bash
declare -r filenames="$(git diff --name-only old-master..defaults-to)"
declare -r directories="$(echo "$filenames" | xargs -n1 dirname | sort -u | sed -e '/^keras\b$/d ; /^keras\/optimizers\b$/d ; /^keras\/saving\/legacy\b$/d ; /^keras\/saving\b$/d')"

# Create branch, commit, checkout files into it, push up
while read -r d; do
  branch="${d//\//.}-defaults-to";
  git checkout -b "${branch}" old-master

  pat='^'"$d"'/*'
  while read -r f; do
    if [[ "$f" =~ $pat ]]; then
      git checkout defaults-to -- "$f"
    fi
  done <<< "${filenames}"
  commit_msg='['"$(git diff --cached --name-only | tr '\n' ',')"
  git commit -S -m "${commit_msg%?}]"' Standardise docstring usage of "Default to"' && \
  git push --set-upstream mine "$branch";
done <<< "${directories}"

# Create PRs
while read -r d; do
  branch="${d//\//.}-defaults-to";
  git checkout "${branch}" &&    gh pr create \
      --title '['"${d}"'] Standardise docstring usage of "Default to"' \
      --body 'This is one of many PRs. Discussion + request to split into multiple PRs @ #17748' ;
done <<< "${directories}"
```