Minor improvements and code refactoring in backend.py
keras-team/keras pull request #17746
Opened 2023-03-30 21:44 UTC by Frightera

Small changes in backend.py, some of were discussed in the PR #17651

2023-04-04 18:03 UTC, qlzh727 requested changes

2023-04-04 18:03 UTC, qlzh727 commented on keras/backend.py
> +        output = softmax(output, axis=axis)
I think redirect to an extra level of internal function is unnecessary. Please keep the existing code.

2023-04-04 21:07 UTC, qlzh727 approved these changes

2023-04-06 16:38 UTC, haifeng-jin commented
The copybara created CL needs to be synced before submission. What do we do in this case? @qlzh727

2023-04-06 19:10 UTC, merged