Add `ScaleInvariantError` Loss
keras-team/keras pull request #17754
Opened 2023-04-03 19:22 UTC by awsaf49

This PR will add `ScaleInvariantError (SIE)`  loss as mentioned in this issue, #17719

2023-04-04 18:36 UTC, awsaf49 commented
@qlzh727 Hi, 
While writing test cases for loss, I observed an issue with the mask function and its impact on `ReductionV2`. Specifically, I noticed that the use of mask (to avoid invalid depth) caused a loss of shape in y_true and y_pred, ultimately converting them into `1D` vectors. Additionally, since the loss function contains `log`, multiplying the mask to zero values is not a straightforward solution.

In the context of Depth Estimation, it is essential to consider the occurrence of invalid depths (i.e., depth = 0) due to sensor limitations. In fact, two of the most popular datasets used for Depth Estimation, KITTI and NYU-Depth-V2, contain instances of invalid depth.

Also not sure if we can avoid mask as in Depth Estimation, `invalid depths ( depth = 0)` are very likely to happen due to sensor. Two most popular dataset **KITTI** and **NYU-Depth-V2** contains invalid depth.

Any thoughts on what should we do?

2023-04-06 21:35 UTC, rchao requested changes
Thanks for the PR! Can you also add unit test to cover the behavior of the loss class/function?

2023-04-17 01:20 UTC, fchollet reviewed
Thank you for the PR! Looks good!

2023-04-17 01:20 UTC, fchollet commented on keras/losses.py
> +    ```
Add: `python`

2023-04-17 01:20 UTC, fchollet commented on keras/losses.py
> +    Standalone usage:
`Example:`

2023-04-17 01:20 UTC, fchollet commented on keras/losses.py
> +        Args:
Please fix indent (4 spaces)

Also: please move the Args section to the class docstring and remove this docstring.

2023-04-17 01:20 UTC, fchollet commented on keras/losses.py
> +    "keras.metrics.scale_invariant_error",
Please do not export it as a metric for the time being.

2023-04-17 01:20 UTC, fchollet commented on keras/losses.py
> +    Args:
Please fix indent (4 spaces)

2023-04-17 01:20 UTC, fchollet commented on keras/losses.py
> +    Standalone usage:
`Example:`

2023-05-19 11:51 UTC, awsaf49 commented
@fchollet @rchao could you please check?

2023-05-27 01:09 UTC, awsaf49 commented
@divyashreepathihalli any update?

2023-09-19 16:27 UTC, sachinprasadhs commented
Hello, Thank you for submitting a pull request.

We're currently in the process of migrating the new `Keras 3 code base` from `keras-team/keras-core` to `keras-team/keras`. 
Consequently, merging this PR is not possible at the moment. After the migration is successfully completed, feel free to reopen this PR at `keras-team/keras` if you believe it remains relevant to the `Keras 3 code base`. If instead this PR fixes a bug or security issue in legacy `tf.keras`, you can instead reopen the PR at `keras-team/tf-keras`, which hosts the `TensorFlow-only`, legacy version of `Keras`.

2023-09-19 16:27 UTC, closed without merging