[keras/datasets] Standardise docstring usage of "Default to"
keras-team/keras pull request #17955
Opened 2023-04-13 00:43 UTC by SamuelMarks

This is one of many PRs. Discussion + request to split into multiple PRs @ #17748

2023-04-19 20:56 UTC, qlzh727 requested changes

2023-04-19 20:56 UTC, qlzh727 commented on keras/datasets/imdb.py
> +          Any longer sequence will be truncated. None, means no truncation.
Please quote the None here.

2023-04-19 20:56 UTC, qlzh727 commented on keras/datasets/reuters.py
> +          Any longer sequence will be truncated. None means no truncation.
Same.

2023-04-19 20:56 UTC, qlzh727 commented on keras/datasets/reuters.py
> +          `oov_char` value in the dataset. 0 means no words are
Same for 0.

2023-04-20 02:40 UTC, SamuelMarks commented on keras/datasets/reuters.py
> +          Any longer sequence will be truncated. None means no truncation.
Fixed

2023-04-20 02:40 UTC, SamuelMarks commented on keras/datasets/reuters.py
> +          `oov_char` value in the dataset. 0 means no words are
Fixed

2023-04-20 02:40 UTC, SamuelMarks commented on keras/datasets/imdb.py
> +          Any longer sequence will be truncated. None, means no truncation.
Fixed

2023-04-21 15:08 UTC, gbaned commented
Hi @SamuelMarks Can you please resolve conflicts? Thank you!

2023-04-23 19:45 UTC, SamuelMarks commented
@gbaned Fixed

2023-04-24 17:42 UTC, qlzh727 approved these changes

2023-04-24 17:43 UTC, qlzh727 requested changes
Please fix the lint error.

2023-04-25 03:31 UTC, SamuelMarks commented
Fixed

2023-04-25 16:57 UTC, qlzh727 approved these changes

2023-04-26 17:56 UTC, merged