[keras/layers/activation] Standardise docstring usage of "Default to"
keras-team/keras pull request #17961
Opened 2023-04-13 00:43 UTC by SamuelMarks

This is one of many PRs. Discussion + request to split into multiple PRs @ #17748

2023-04-19 20:55 UTC, qlzh727 requested changes

2023-04-19 20:55 UTC, qlzh727 commented on keras/layers/activation/relu.py
> +      max_value: Float >= 0. Maximum activation value. None means unlimited.
Please quote the None here.

2023-04-20 02:43 UTC, SamuelMarks commented on keras/layers/activation/relu.py
> +      max_value: Float >= 0. Maximum activation value. None means unlimited.
Fixed

2023-04-20 17:31 UTC, qlzh727 commented
Please resolve the merge conflicit.

2023-04-23 19:19 UTC, SamuelMarks commented
@qlzh727 Resolved

2023-04-24 17:41 UTC, qlzh727 approved these changes

2023-04-26 21:41 UTC, merged