[keras/saving/legacy/saved_model] Standardise docstring usage of "Default to"
keras-team/keras pull request #17978
Opened 2023-04-13 01:18 UTC by SamuelMarks

This is one of many PRs. Discussion + request to split into multiple PRs @ #17748

2023-04-19 20:44 UTC, qlzh727 requested changes

2023-04-19 20:44 UTC, qlzh727 commented on keras/saving/legacy/saved_model/save.py
> +        Disabling this will decrease serialization time and filesize, but
file size should be two words.

2023-04-20 03:00 UTC, SamuelMarks commented on keras/saving/legacy/saved_model/save.py
> +        Disabling this will decrease serialization time and filesize, but
Fixed

2023-04-20 17:13 UTC, qlzh727 approved these changes

2023-05-03 17:36 UTC, merged