[keras/optimizers/legacy] Standardise docstring usage of "Default to"
keras-team/keras pull request #17975
Opened 2023-04-13 01:18 UTC by SamuelMarks

This is one of many PRs. Discussion + request to split into multiple PRs @ #17748

2023-04-19 20:47 UTC, qlzh727 requested changes

2023-04-19 20:47 UTC, qlzh727 commented on keras/optimizers/legacy/optimizer_v2.py
> +          name: Optional name for the returned operation. When None, uses the
Please quote the None her.

2023-04-19 20:47 UTC, qlzh727 commented on keras/optimizers/legacy_learning_rate_decay.py
> +        power of the polynomial. Linear is default. Defaults to `1.0`.
Let's remove `Linear is default.`

2023-04-20 03:04 UTC, SamuelMarks commented on keras/optimizers/legacy_learning_rate_decay.py
> +        power of the polynomial. Linear is default. Defaults to `1.0`.
Fixed

2023-04-20 03:04 UTC, SamuelMarks commented on keras/optimizers/legacy/optimizer_v2.py
> +          name: Optional name for the returned operation. When None, uses the
Fixed

2023-04-20 17:14 UTC, qlzh727 approved these changes

2023-04-21 17:26 UTC, merged