Updating split range from [0, 1] to (0, 1) in keras.utils.split_dataset
keras-team/keras pull request #18028
Opened 2023-04-21 15:34 UTC by SuryanarayanaY

In the `tf.keras.utils.split_dataset` API , that can be used to split a dataset into left and right parts, the documentation states it splits dataset into `left half` and `right half` where the parts need not be equal parts.The split can be anything in range (0, 1). Hence I thought to replace the word `half` with `part`. 

Also in the `Args` section of documentation and `exception handling` in `source code` the range for split used as `[0, 1]` which is not a correct notation as 0 and 1 are actually not inclusive in the range and raises exception if we use either `0 or 1 `for either of `left_size` or `right_size` for splitting the dataset. Hence I have replaced `[0, 1] `with `(0, 1)` to make it more intuitive. Thanks.

2023-04-21 16:44 UTC, fchollet commented on keras/utils/dataset_utils.py
> +        left_size: If float (in the range `(0, 1)`), it signifies
Please keep the brackets for the range -- it mimics math notation for ranges.

2023-04-21 16:44 UTC, fchollet commented on keras/utils/dataset_utils.py
> +    """Split a dataset into a left part and a right part (e.g. train / test).
OK

2023-05-04 08:16 UTC, gbaned commented
Hi @SuryanarayanaY Can you please check @fchollet's comments ? Thank you!

2023-06-01 07:22 UTC, gbaned commented
Hi @SuryanarayanaY Any update on this PR? Please. Thank you!

2023-06-08 08:20 UTC, gbaned commented
Hi @SuryanarayanaY Any update on this PR? Please. Thank you!

2023-06-10 18:22 UTC, ananthmuppidi commented
hey @gbaned, new to Keras. Is this a good first issue?

2023-06-13 06:58 UTC, SuryanarayanaY commented
Added my comments above

2023-06-21 05:27 UTC, gbaned commented
Hi @fchollet Can you please assist on above [comments](https://github.com/keras-team/keras/pull/18028#discussion_r1227620717) from @SuryanarayanaY. Thank you!

2023-06-22 17:18 UTC, fchollet commented
The notation `(0, 1)` is ambiguous and not standard. Instead, you can just say "[0, 1] (excluding the boundary values 0 and 1)" which is clearer.

2023-06-29 17:19 UTC, fchollet commented on keras/utils/dataset_utils.py
> +        left_size: If float (in the range "[0, 1] (excluding the boundary values 0 and 1)"), it signifies
- use backticks for the `[]` range
- remove `"` quotes
- make sure the lines are under 80 chars

2023-06-29 17:19 UTC, fchollet commented on keras/utils/dataset_utils.py
> +        right_size: If float (in the range `(0, 1)`), it signifies
`[0, 1]`

2023-07-17 06:06 UTC, gbaned commented
Hi @SuryanarayanaY Can you please check @fchollet's comments and keep us posted ? Thank you!

2023-07-19 12:23 UTC, SuryanarayanaY commented
Apologies for the delay. Done the changes as requested. Thanks

2023-07-27 16:26 UTC, grasskin commented
Hi @SuryanarayanaY, thank you for the PR! Could you fix 
```
keras/utils/dataset_utils.py:402:81: E501 line too long (101 > 80 characters)
keras/utils/dataset_utils.py:417:81: E501 line too long (102 > 80 characters)
```
and run `black` for code style.

2023-08-01 13:46 UTC, SuryanarayanaY commented
Done the changes

2023-08-14 08:48 UTC, grasskin requested changes

2023-08-14 08:48 UTC, grasskin commented on keras/utils/dataset_utils.py
> +          pack in the left dataset.If integer, it signifies the number of
Please fix the end of sentence spacing `dataset.If`

2023-08-14 08:48 UTC, grasskin commented on keras/utils/dataset_utils.py
> +          samples to pack in the left dataset.If `None`, it uses the complement
Same as above

2023-08-14 08:48 UTC, grasskin commented on keras/utils/dataset_utils.py
> +            "within the range '[0, 1] (excluding the boundary values 0 and 1)'."
`[0, 1]` for consistency

2023-08-14 08:48 UTC, grasskin commented on keras/utils/dataset_utils.py
> +            "within the range '[0, 1] (excluding the boundary values 0 and 1)'."
`[0, 1]` for consistency

2023-08-22 07:15 UTC, gbaned commented
Hi @SuryanarayanaY Can you please check @grasskin's comments and keep us posted ? Thank you!

2023-08-24 04:40 UTC, SuryanarayanaY commented
Apologies for the delay.Done the suggested changes.

2023-08-25 14:26 UTC, grasskin approved these changes
LGTM

2023-09-19 16:26 UTC, closed without merging