Update indentation level - activations.py
keras-team/keras pull request #18036
Opened 2023-04-21 17:02 UTC by Frightera

This PR changes the indentation level of the docstrings to 4 spaces.

2023-04-24 05:31 UTC, haifeng-jin requested changes
Thanks for the PR!

2023-04-24 05:31 UTC, haifeng-jin commented on keras/activations.py
>      """
We keep these markdowns always on the same line and add a `# noqa: E501` after `"""`.

2023-04-24 05:31 UTC, haifeng-jin commented on keras/activations.py
> +            serialization.
Add "Defaults to False." to the end.

2023-04-24 05:31 UTC, haifeng-jin commented on keras/activations.py
> +            deserialization.
same here.

2023-04-24 09:22 UTC, haifeng-jin approved these changes

2023-05-04 17:04 UTC, haifeng-jin approved these changes

2023-05-05 11:13 UTC, Frightera commented
@gbaned Any idea why copybara closed the PR without merging it?

2023-05-05 11:19 UTC, Frightera commented
@gbaned Any idea why copybara closed the PR without merging it?

2023-05-09 06:15 UTC, gbaned commented
> @gbaned  Any idea why copybara closed the PR without merging it?

Hi @Frightera I can see this PR is still open, can you please provide PR which is closed by copybara without merging it. Thank you!

2023-05-09 07:04 UTC, Frightera commented
Hi @gbaned I meant #18036.

2023-05-31 22:29 UTC, merged