Improve error message for input data to fit.
keras-team/keras pull request #18042
Opened 2023-04-21 23:03 UTC by tomrtk

The open PR for issue #16202 looks to be dead, and having conflicts. So I have added some checks in `DataHandler` to catch empty input and steps. I did not edit the error message in `fit` like the last PR did, as it looks to have been updated already.

This PR improve error message to give more useful feedback:
- if passing empty dataset or array as input data
- if passing `steps_per_epoch=0`

to `Model.fit()` by adding checks in `DataHandler`.

Resolve #16202

2023-04-24 17:39 UTC, qlzh727 requested changes

2023-04-24 17:39 UTC, qlzh727 commented on keras/engine/data_adapter.py
> +                "Got argument `steps_per_epoch=0` passed to `fit()`."
Let's update this error message to be

"Unexpected value for `steps_per_epoch`. Received value is 0. Please check the docstring for `model.fit()` for supported values."

2023-04-24 17:39 UTC, qlzh727 commented on keras/engine/data_adapter.py
> +            raise ValueError("Expected input data to `fit()` to be non-empty.")
Note that this method can be called for model.eval/predict as well, so let's remove the model.fit() from the message.

2023-07-04 06:55 UTC, gbaned commented
> there has not been any progress on this pr for a while, so I just want to make sure there is no blockers from my side?

Hi @tomrtk Sorry for the delay, this PR is in awaiting review status. No blockers from your end. Thank you!
Hi @qlzh727 Can you please review this PR ? Thank you!

2023-07-05 16:07 UTC, qlzh727 commented
Somehow it was blocked in the gerrit review, let me try to kick it again.

2023-07-12 18:06 UTC, merged