Some cleanup // Optimizers
keras-team/keras pull request #18124
Opened 2023-05-15 15:40 UTC by Frightera

This PR:
* Migrates docstrings into 4 indents 
* Removes unused args in adam & adamw

2023-05-18 17:21 UTC, rchao commented on keras/optimizers/ftrl.py
> +             that takes no arguments and returns the actual value to use. The
Thanks for the PR! Looks like some of those lines don't have the proper indentation (indent 4) - can you fix this?

2023-05-21 14:54 UTC, rchao approved these changes
Thanks!

2023-05-22 18:31 UTC, haifeng-jin requested changes
Just one minor comment and we are ready to go. Thanks!

2023-05-22 18:31 UTC, haifeng-jin commented on keras/optimizers/adagrad.py
> +        stability.
We need 4 more indents here.

2023-05-22 18:44 UTC, Frightera commented on keras/optimizers/adagrad.py
> +        stability.
Ahh right.

2023-05-22 18:50 UTC, haifeng-jin approved these changes

2023-05-23 10:11 UTC, merged