Modify the documentation of padding="same" for conv layer in conv1d.py
keras-team/keras pull request #18142
Opened 2023-05-19 15:22 UTC by tilakrayal

Modify the documentation of **padding="same"** for conv layer in `conv1d.py`

2023-05-24 15:09 UTC, haifeng-jin requested changes
Thanks for the update!

2023-05-24 15:09 UTC, haifeng-jin commented on keras/layers/convolutional/conv1d.py
> +        evenly to the left/right or up/down of the input.When padding=
Insert a space between "input.When".

2023-05-24 15:09 UTC, haifeng-jin commented on keras/layers/convolutional/conv1d.py
> +        evenly to the left/right or up/down of the input.When padding=
move padding to the next line and make it like `padding="same"`. Format the line lengths for the rest of the lines accordingly.

2023-06-01 16:06 UTC, haifeng-jin requested changes
We still have the following lint errors. You can also see it yourself in the CI.
```
keras/layers/convolutional/conv1d.py:78:63: W291 trailing whitespace
keras/layers/convolutional/conv1d.py:79:71: W291 trailing whitespace
```

2023-06-08 08:30 UTC, gbaned commented
Hi @tilakrayal Can you please check @haifeng-jin's comments and keep us posted ? Thank you!

2023-06-19 07:20 UTC, gbaned commented
Hi @tilakrayal Any update on this PR? Please. Thank you!

2023-07-18 02:10 UTC, closed without merging