Avoid import tensorflow directly
keras-team/keras pull request #18655
Opened 2023-10-19 22:41 UTC by haifeng-jin

People may use other backends without installing TF.

2023-10-19 22:54 UTC, qlzh727 requested changes

2023-10-19 22:54 UTC, qlzh727 commented on keras/distribution/distribution_lib.py
> +from keras.utils.module_utils import tensorflow as tf
Thanks for the fix. Can we move this to the place that tf is used (eg the distribute_dataset method.)

2023-10-20 08:31 UTC, fchollet commented
Why was this not caught by our dedicated integration test?

2023-10-20 17:11 UTC, haifeng-jin commented
> Why was this not caught by our dedicated integration test?

I don't think we uninstalled tensorflow for the jax and pytorch backend tests. Should we? or there are some test cases that always uses tensorflow no matter what backend it is.

2023-10-21 08:44 UTC, fchollet approved these changes
LGTM

2023-10-21 08:44 UTC, merged

2023-10-23 17:28 UTC, qlzh727 commented
Thanks for the fix.