Update adafactor.py
keras-team/keras pull request #18673
Opened 2023-10-23 18:08 UTC by gautam1858

1. Reduced redundancy by using a single index variable (idx) for accessing _r, _c, and _v. 
2. Eliminated repeated calls to ops.cast for learning_rate and gradient. 
3. Grouped related operations for better readability.

2023-10-25 22:47 UTC, haifeng-jin requested changes
Thanks for the PR! It breaks the code style check. Would you mind take a look?

2023-10-25 22:47 UTC, haifeng-jin commented on keras/optimizers/adafactor.py
> -        """Update step given gradient and the associated model variable."""
Why is this line removed, please?

2023-10-28 20:21 UTC, mihaimaruseac commented
Please don't use "add file"/"update file"/"fix file"/etc. commit messages. These are hard to reason about when looking at the history of the file/repository. Instead, please write explanatory git commit messages.

The commit message is also the title of the PR if the PR has only one commit. It is thus twice important to have commit messages that are relevant, as PRs would be easier to understand and easier to analyze in search results.

For how to write good quality git commit messages, please consult https://cbea.ms/git-commit/

2023-10-28 20:22 UTC, mihaimaruseac commented
The author has sent 3 spam PRs on TF repo and one PR that got merged.

2023-10-31 08:02 UTC, gautam1858 commented
> Thanks for the PR! It breaks the code style check. Would you mind take a look?

Sure I will look into it

2023-12-01 08:08 UTC, gbaned commented
Hi @gautam1858 Any update on this PR? Please. Thank you!

2023-12-21 05:05 UTC, closed without merging