Keras upgrade cait
keras-team/keras pull request #18700
Opened 2023-10-27 20:53 UTC by madhusshivakumar

Upgrade Keras to the Latest Version and Adapt the Code for Compatibility

In this commit, I have upgraded the Keras library to its latest version to take advantage of new features and improvements. Additionally, I have made necessary code modifications to maintain the previous functionality while utilizing the updated Keras API.

Key Changes:

Upgraded Keras to version 3.0
Updated deprecated Keras functions to their latest equivalents.
Tested the code to verify that it functions correctly with the new Keras version.
These changes aim to keep our project up to date with the latest tools and technologies while preserving the integrity of our existing functionality.

git diff:

```
index fc130dc..1a81961 100644
--- a/examples/vision/cait.py
+++ b/examples/vision/cait.py
@@ -49,9 +49,11 @@ from urllib.request import urlopen
 import matplotlib.pyplot as plt
 import numpy as np
 import PIL
-import tensorflow as tf
-from tensorflow import keras
-from tensorflow.keras import layers
+# import tensorflow as tf
+import keras
+# from tensorflow import keras
+from keras import layers
+# from tensorflow.keras import layers
 
 """
 ## The LayerScale layer
@@ -105,7 +107,7 @@ class LayerScale(layers.Layer):
 
     def __init__(self, init_values: float, projection_dim: int, **kwargs):
         super().__init__(**kwargs)
-        self.gamma = tf.Variable(init_values * tf.ones((projection_dim,)))
+        self.gamma = keras.ops.Var(init_values * keras.ops.ones((projection_dim,)))
 
     def call(self, x, training=False):
:...skipping...
diff --git a/examples/vision/cait.py b/examples/vision/cait.py
index fc130dc..1a81961 100644
--- a/examples/vision/cait.py
+++ b/examples/vision/cait.py
@@ -49,9 +49,11 @@ from urllib.request import urlopen
 import matplotlib.pyplot as plt
 import numpy as np
 import PIL
-import tensorflow as tf
-from tensorflow import keras
-from tensorflow.keras import layers
+# import tensorflow as tf
+import keras
+# from tensorflow import keras
+from keras import layers
+# from tensorflow.keras import layers
 
 """
 ## The LayerScale layer
@@ -105,7 +107,7 @@ class LayerScale(layers.Layer):
 
     def __init__(self, init_values: float, projection_dim: int, **kwargs):
         super().__init__(**kwargs)
-        self.gamma = tf.Variable(init_values * tf.ones((projection_dim,)))
+        self.gamma = keras.ops.Var(init_values * keras.ops.ones((projection_dim,)))
 
     def call(self, x, training=False):
         return x * self.gamma
@@ -136,9 +138,9 @@ class StochasticDepth(layers.Layer):
     def call(self, x, training=False):
         if training:
             keep_prob = 1 - self.drop_prob
-            shape = (tf.shape(x)[0],) + (1,) * (len(tf.shape(x)) - 1)
-            random_tensor = keep_prob + tf.random.uniform(shape, 0, 1)
-            random_tensor = tf.floor(random_tensor)
+            shape = (keras.ops.shape(x)[0],) + (1,) * (len(keras.ops.shape(x)) - 1)
+            random_tensor = keep_prob + keras.random.uniform(shape, 0, 1)
+            random_tensor = keras.ops.floor(random_tensor)
             return (x / keep_prob) * random_tensor
         return x
 
@@ -210,42 +212,42 @@ class ClassAttention(layers.Layer):
 
     def call(self, x, training=False):
         batch_size, num_patches, num_channels = (
-            tf.shape(x)[0],
-            tf.shape(x)[1],
-            tf.shape(x)[2],
+            keras.ops.shape(x)[0],
+            keras.ops.shape(x)[1],
+            keras.ops.shape(x)[2],
         )
 
         # Query projection. `cls_token` embeddings are queries.
-        q = tf.expand_dims(self.q(x[:, 0]), axis=1)
-        q = tf.reshape(
+        q = keras.ops.expand_dims(self.q(x[:, 0]), axis=1)
+        q = keras.ops.ravel(
             q, (batch_size, 1, self.num_heads, num_channels // self.num_heads)
         )  # Shape: (batch_size, 1, num_heads, dimension_per_head)
-        q = tf.transpose(q, perm=[0, 2, 1, 3])
-        scale = tf.cast(self.scale, dtype=q.dtype)
+        q = keras.ops.swapaxes(q, perm=[0, 2, 1, 3])
+        scale = keras.ops.cast(self.scale, dtype=q.dtype)
         q = q * scale
 
         # Key projection. Patch embeddings as well the cls embedding are used as keys.
         k = self.k(x)
-        k = tf.reshape(
+        k = keras.ops.ravel(
             k, (batch_size, num_patches, self.num_heads, num_channels // self.num_heads)
         )  # Shape: (batch_size, num_tokens, num_heads, dimension_per_head)
-        k = tf.transpose(k, perm=[0, 2, 1, 3])
+        k = keras.ops.swapaxes(k, perm=[0, 2, 1, 3])
 
         # Value projection. Patch embeddings as well the cls embedding are used as values.
         v = self.v(x)
-        v = tf.reshape(
+        v = keras.ops.ravel(
             v, (batch_size, num_patches, self.num_heads, num_channels // self.num_heads)
         )
-        v = tf.transpose(v, perm=[0, 2, 1, 3])
+        v = keras.ops.swapaxes(v, perm=[0, 2, 1, 3])
 
         # Calculate attention scores between cls_token embedding and patch embeddings.
-        attn = tf.matmul(q, k, transpose_b=True)
-        attn = tf.nn.softmax(attn, axis=-1)
+        attn = keras.ops.matmul(q, k, transpose_b=True)
+        attn = keras.ops.softmax(attn, axis=-1)
         attn = self.attn_drop(attn, training)
 
-        x_cls = tf.matmul(attn, v)
-        x_cls = tf.transpose(x_cls, perm=[0, 2, 1, 3])
-        x_cls = tf.reshape(x_cls, (batch_size, 1, num_channels))
+        x_cls = keras.ops.matmul(attn, v)
+        x_cls = keras.ops.swapaxes(x_cls, perm=[0, 2, 1, 3])
+        x_cls = keras.ops.ravel(x_cls, (batch_size, 1, num_channels))
         x_cls = self.proj(x_cls)
         x_cls = self.proj_drop(x_cls, training)
 
@@ -301,40 +303,40 @@ class TalkingHeadAttention(layers.Layer):
         self.proj_drop = layers.Dropout(dropout_rate)
 
     def call(self, x, training=False):
-        B, N, C = tf.shape(x)[0], tf.shape(x)[1], tf.shape(x)[2]
+        B, N, C = keras.ops.shape(x)[0], keras.ops.shape(x)[1], keras.ops.shape(x)[2]
 
         # Project the inputs all at once.
         qkv = self.qkv(x)
 
         # Reshape the projected output so that they're segregated in terms of
         # query, key, and value projections.
-        qkv = tf.reshape(qkv, (B, N, 3, self.num_heads, C // self.num_heads))
+        qkv = keras.ops.ravel(qkv, (B, N, 3, self.num_heads, C // self.num_heads))
 
         # Transpose so that the `num_heads` becomes the leading dimensions.
         # Helps to better segregate the representation sub-spaces.
-        qkv = tf.transpose(qkv, perm=[2, 0, 3, 1, 4])
-        scale = tf.cast(self.scale, dtype=qkv.dtype)
+        qkv = keras.ops.swapaxes(qkv, perm=[2, 0, 3, 1, 4])
+        scale = keras.ops.cast(self.scale, dtype=qkv.dtype)
         q, k, v = qkv[0] * scale, qkv[1], qkv[2]
 
         # Obtain the raw attention scores.
-        attn = tf.matmul(q, tf.transpose(k, perm=[0, 1, 3, 2]))
+        attn = keras.ops.matmul(q, keras.ops.swapaxes(k, perm=[0, 1, 3, 2]))
 
         # Linear projection of the similarities between the query and key projections.
-        attn = self.proj_l(tf.transpose(attn, perm=[0, 2, 3, 1]))
+        attn = self.proj_l(keras.ops.swapaxes(attn, perm=[0, 2, 3, 1]))
 
         # Normalize the attention scores.
-        attn = tf.transpose(attn, perm=[0, 3, 1, 2])
-        attn = tf.nn.softmax(attn, axis=-1)
+        attn = keras.ops.swapaxes(attn, perm=[0, 3, 1, 2])
+        attn = keras.ops.softmax(attn, axis=-1)
 
         # Linear projection on the softmaxed scores.
-        attn = self.proj_w(tf.transpose(attn, perm=[0, 2, 3, 1]))
-        attn = tf.transpose(attn, perm=[0, 3, 1, 2])
+        attn = self.proj_w(keras.ops.swapaxes(attn, perm=[0, 2, 3, 1]))
+        attn = keras.ops.swapaxes(attn, perm=[0, 3, 1, 2])
         attn = self.attn_drop(attn, training)
 
         # Final set of projections as done in the vanilla attention mechanism.
-        x = tf.matmul(attn, v)
-        x = tf.transpose(x, perm=[0, 2, 1, 3])
-        x = tf.reshape(x, (B [...]

2023-10-27 20:57 UTC, madhusshivakumar commented
#18699

2023-10-30 04:50 UTC, divyashreepathihalli requested changes
@madhusshivakumar thank you for the PR. I have left a few comments. Please make the changes and see if that resolves the issue you are facing. I have also added suggestions on the issue you have filed, please try that out if this does not work.

2023-10-30 04:50 UTC, divyashreepathihalli commented on examples/keras_io/vision/cait.py
> +        q = keras.ops.ravel(
use `keras.ops.reshape` to replace `tf.reshape`

2023-10-30 04:50 UTC, divyashreepathihalli commented on examples/keras_io/vision/cait.py
> +                keras.ops.average(x[:, 1:], axis=1)
use `keras.ops.mean` and specify the axis as an equivalent to `tf.reduce_mean`

2023-10-30 04:50 UTC, divyashreepathihalli commented on examples/keras_io/vision/cait.py
> +    attentions = keras.ops.resize(
use `keras.ops.image.resize` as an equivalent to `tf.image.resize`.

2023-10-30 04:50 UTC, divyashreepathihalli commented on examples/keras_io/vision/cait.py
> +image_resized = keras.ops.resize(
use `keras.ops.image.resize` as an equivalent to `tf.image.resize`

2023-10-30 04:50 UTC, divyashreepathihalli commented on examples/keras_io/vision/cait.py
> +        k = keras.ops.ravel(
use keras.ops.reshape to replace tf.reshape

2023-10-30 04:50 UTC, divyashreepathihalli commented on examples/keras_io/vision/cait.py
> +        v = keras.ops.ravel(
use keras.ops.reshape to replace tf.reshape

2023-10-30 04:50 UTC, divyashreepathihalli commented on examples/keras_io/vision/cait.py
> +        x_cls = keras.ops.ravel(x_cls, (batch_size, 1, num_channels))
use keras.ops.reshape to replace tf.reshape

2023-10-30 04:50 UTC, divyashreepathihalli commented on examples/keras_io/vision/cait.py
> +        qkv = keras.ops.ravel(qkv, (B, N, 3, self.num_heads, C // self.num_heads))
use keras.ops.reshape to replace tf.reshape

2023-10-30 04:50 UTC, divyashreepathihalli commented on examples/keras_io/vision/cait.py
> +        x = keras.ops.ravel(x, (B, N, C))
use keras.ops.reshape to replace tf.reshape

2023-12-06 18:55 UTC, fchollet commented
This example has already been updated on keras.io, so this PR is no longer needed. Thanks!

2023-12-06 18:55 UTC, closed without merging